title: GitHub Pages learning
author: Dmitry Vdovichencko
email: your-email@domain.com
description: GitHub Pages learning course. Created with Jekyll hosting with GitHub Pages.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
